name: Windows/mingw
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/workflows/macos.yml'
      - '.github/workflows/windows.yml'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/workflows/macos.yml'
      - '.github/workflows/windows.yml'
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        qt_ver: [5.14.2]
        qt_target: [desktop]
        qt_arch: [win64_mingw73]
        include:
          - qt_arch: win64_mingw73
            qt_arch_install: mingw64_73
    env:
      targetName: q5go
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.0.0
        with:
          # Version of Qt to install
          version: ${{ matrix.qt_ver }}
          # Target platform for build
          target: ${{ matrix.qt_target }}
          # Architecture for Windows/Android
          arch: ${{ matrix.qt_arch }}

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: true

      - name: build-mingw
        shell: cmd
        env:
          archiveName: ${{ env.targetName }}-${{ matrix.qt_arch }}
        run: |
          mkdir build
          cd build
          qmake -r CONFIG+=release CONFIG+=qtquickcompiler ..\src\q5go.pro DEFINES+=GITHUB_CI_BUILD
          make
          dir
          dir release
          cd ..
          mkdir output
          mkdir output\%archiveName%
          copy build\release\%targetName%.exe output\%archiveName%\
          qtenv2
          windeployqt --qmldir . output\%archiveName%\%targetName%.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ env.targetName }}-${{ matrix.qt_arch }}
          path: output
